#!/bin/bash
# ==========================================================
# 3x-ui Full Installer with Summary Output for VManager
# ==========================================================

LOG_FILE="/var/log/vm_install_3xui.log"
SUMMARY_FILE="/root/3xui.txt"
exec > >(tee -a "$LOG_FILE") 2>&1
set -e

echo "========== $(date) Starting 3x-ui installation =========="

export DEBIAN_FRONTEND=noninteractive
dpkg --configure -a || true
apt --fix-broken install -y || true
apt update -y
apt install -y curl wget sudo tar lsof net-tools cron jq

# --- Download and install 3x-ui ---
curl -L -o /tmp/install_3xui.sh https://raw.githubusercontent.com/MHSanaei/3x-ui/master/install.sh
chmod +x /tmp/install_3xui.sh
bash /tmp/install_3xui.sh <<EOF
n
EOF

systemctl enable x-ui || true
systemctl restart x-ui || true

# --- Extract data from config ---
CONFIG="/usr/local/x-ui/bin/config.json"
if [ -f "$CONFIG" ]; then
  LOGIN=$(jq -r '.webUser' "$CONFIG" 2>/dev/null || echo "admin")
  PASSWORD=$(jq -r '.webPassword' "$CONFIG" 2>/dev/null || echo "admin123")
  PORT=$(jq -r '.webPort' "$CONFIG" 2>/dev/null || echo "54321")
else
  LOGIN="admin"
  PASSWORD="admin123"
  PORT="54321"
fi

IP=$(hostname -I | awk '{print $1}')

cat <<EOF2 | tee "$SUMMARY_FILE"

✅ 3x-ui installed successfully!
echo "---------------------------------------"
echo "Actual login information generated by 3x-ui:"
grep -A 5 'Username:' /var/log/vm_install_3xui.log || true
echo "---------------------------------------"
Logs:      $LOG_FILE
Summary:   $SUMMARY_FILE
EOF2

echo "[DONE] $(date) 3x-ui installation complete."
